### ISSUE TITLE
so i started the live and after live bot send a lot already uploader videos

### ISSUE THREAD

**Issue by luktvpl** [James-Bennett-295/npm-youtube-notifs#2]
![image](https://user-images.githubusercontent.com/92756992/156846284-b08d8257-69d3-4778-a34c-e1fddb545805.png)
like you see on this picture my bot send multiple videos i've uploaded long ago after the live ended

**Comment by James-Bennett-295** [comment]
It seems to just be an anomaly, but I published a new version just now (2.8.5) which contains a possible fix
