### ISSUE TITLE
Getting ERR_REQUIRE_ESM with v3.0.0

### ISSUE THREAD

**Issue by reddvid** [James-Bennett-295/npm-youtube-notifs#3]
This issue only happens on the latest version 3.0.0, as I wanted to test the latest version since 2.9.7 (wanted) sends duplicate message (same video) at random times.

**Comment by James-Bennett-295** [comment]
Please create a new issue on the new repo [here](https://github.com/James-Bennett-295/npm-yt-notifs/issues/new).
