### ISSUE TITLE
Question: Is it dangerous to set the interval to a low number?

### ISSUE THREAD

**Issue by themetalfleece** [James-Bennett-295/npm-youtube-notifs#9]
Hey there, awesome work on the package, it's very useful!

I have a question, what could happen if I set the interval to 1 minute and have it run indefinitely? Could I be rate limited, or hit some quota limit?

I think that this could also be useful to add in the Readme :)

Thanks!

**Comment by James-Bennett-295** [comment]
An interval of 1 minute has worked fine for me in the past.
I have been unable to find the rate limiting information of Youtube's RSS feeds (which this uses), I eventually tried asking ChatGPT, which said that "accessing RSS feeds still falls under the YouTube Data API", and that "YouTube Data API is 10,000 units per day", though it was unable to give me sources on that information when I asked for them. There are 1440 minutes in a day, so if the information ChatGPT gave me is correct, then 1 minute should be fine. Note that if you are subscribing to multiple channels, an RSS request is done for each channel subscribed to on the interval, so how low the interval can be will depend on the amount of channels subscribed to.

**Comment by themetalfleece** [comment]
Gotcha, thanks for your quick reply :)
